# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Formant Analyzer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Formant Analyzer
  pod 'FSLineChart'
  pod 'FDSoundActivatedRecorder'

  target 'Formant AnalyzerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Formant AnalyzerUITests' do
    # Pods for testing
  end

end
