# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Formant Analyzer SwiftUI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Formant Analyzer SwiftUI
  pod 'FSLineChart'
  pod 'FDSoundActivatedRecorder'

  target 'Formant Analyzer SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Formant Analyzer SwiftUIUITests' do
    # Pods for testing
  end

end
